### ISSUE TITLE
Deploy a stage environment with a snapshot of prod data

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplain-lambdas#40]
Need to be able to test the data structures currently in prod, before deploying the changes

Design to easily switch that env to point to prod after smoke testing

**Comment by thebho** [comment]
http://stackoverflow.com/questions/5194552/is-it-possible-to-copy-all-files-from-one-s3-bucket-to-another-with-s3cmd

**Comment by dane-johnson** [comment]
@thebho Is this a duplicate of #31?
