### ISSUE TITLE
Secure Access-Control-Allow-Origin headers

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplain-lambdas#67]
Currently, the Access-Control-Allow-Origin headers accept requests from any url. This should only accept requests from the codes plain url.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by dane-johnson** [comment]
I think this can be set up to echo the calling address, so the end-user will be aware of a man-in-the-middle whilst still being able to access from any IP

**Comment by dane-johnson** [comment]
I have looked into it more and found this practice to be ineffective
