### ISSUE TITLE
Validate Body of POSTs & PUTs

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplain-lambdas#86]
## Expected Behavior

The lambdas which handle POST and PUT requests ought to validate that the requests they receive have the required body, e.g. it must be of the form:
```javascript
{
  "annotations": { ... },
  "AST": { ... },
  "filters": { ... },
  "snippetLanguage": " ... ",
  "readOnly": true/false,
  "snippet": " ... ",
  "snippetTitle": " ... ",
}
```

## Current Behavior

The lambdas do not currently do this checking. If a POST/PUT is made with an invalid body, it may or may not result in a failure.

## Possible Solution

Use a JSON schema validator library of some sort to check the parsed request bodies.

**Comment by solkaz** [comment]
[There's a nice list of data validation libraries in Python](https://awesome-python.com/#data-validation) that we could choose from

**Comment by thebho** [comment]
Reverted because Saving was broken in dev.  https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/lambda/PutSnippet-dev;stream=2017/05/08/%5B$LATEST%5D1fc3632fa7094dfcbb71996c538631aa
