### ISSUE TITLE
Create lambda to get all snippets from an array of organizations

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplain-lambdas#93]
## Expected Behavior
I can send an array of organizations to a Lambda that respond with the list of snippets for each organization. This would require 1 AJAX request from the UI to the lambda, and should return an object like such:
```js
{
  "org_name": [
    // List of snippets
  ],
  // ...
}
```

## Current Behavior
I need to make a new request for each organization a user is a part of, meaning if they are a part of `n` organizations, I must make `n` requests, which is inefficient.

**Comment by dane-johnson** [comment]
This could be accomplished fairly easily. Org dirs should still have index files that can be referenced.
